# Generated by Django 4.0.3 on 2022-04-08 22:11

from django.db import migrations, models
import price.models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to=price.models.filePath)),
            ],
        ),
    ]
